#!/bin/bash
clear
Hello()
{
echo $1. $wish
}
echo "Let's try some functions in scripts"
echo "Type the number of times you want to be wished"
read count
echo
echo "What should I wish you? Good Morning? Guten Morgan? Namaste?"
read wish
echo
i=1
while [ $i -le $count ]
do
# I am passing a parameter to my function
Hello $i
i=$(( $i + 1 ))
done
