#!/bin/bash
clear
echo "Let's try out the concept of arrays in this script."
sleep 2
echo "Type you favourite programming languages"
sleep 1
echo "When you are done, type EOF"

#My array to hold the languages
prog_name=()

count=0
while read name;
do

if [ $name = "EOF" ];
then
sleep 2
break;
else
prog_name[$count]=$name
count=$(( $count + 1 ))
fi

done

echo "\nThank you"
sleep 1
echo "\nHere's what you have entered:"
echo ${prog_name[*]}

echo "See ya later!"

echo "\nIn this script, you have learnt about arrays."
