#!/bin/bash
clear
echo "Let's learn about some special variables."
sleep 2
echo
echo $$
echo "Now that shows you the PID of the current shell."
sleep 2
echo
echo $0
echo "Hey!that's the name of your current script."
sleep 2
echo
echo "The first argument you have passed is $1"
sleep 1
echo "Now..if you don't see anything outputted, that means you have not passed any arguments to this script."
sleep 2
echo "Next time your run this script, pass an argument!"
sleep 2
echo
echo "You have passed $# number of arguments to this script."
sleep 2
echo
echo "You have passed the argument(s) $* to this script."
sleep 2
echo
echo "Let me show you the list of arguments you passed:"
sleep 2
for TOKEN in $*
do
echo -----
echo $TOKEN
done
echo -----
echo "In this script, you have learnt the following commands:"
sleep 0.5
echo "1. To see PID, echo \$\$"
sleep 0.5
echo "2. To see name of script, echo \$0"
sleep 0.5
echo "3. To find number of args, echo \$#"
sleep 0.5
echo "4. To find the args passed, echo \$*"
sleep 0.5
echo "5. To find the nth argument passed, echo \$n. For example, echo \$1"
sleep 0.5
echo "6. The syntax of 'for' loop"
