#!/bin/bash

echo "Let's see if we can check whether files or directories exist."
sleep 2
echo "I am creating variables for directory path and file path."
sleep 1

dire=~/Documents
fname=~/Documents/BashExer/MyBash2

echo
echo "Lemme print them out."
sleep 2

echo The directory is $dire
echo The filename is $fname

echo

echo "Now let's see if I can do a dir check."
sleep 2
if [ -d "$dire" ]; then
echo "Dir exists. My script can see it."
else
echo "Dir doesn't exist."
fi

echo
echo "Now moving on to the file check."
sleep 2
if [ -f "$fname" ]; then
echo "Yes!ma file exists."
else
echo "Nope! I can't find it."
fi

echo "\nIn this script, you have learnt how to check whether files or directories exist."
