#!/bin/bash

#This script shows you how to use variables in bash scripts
clear
echo "Let's create some variables and use them."
sleep 2
echo
FNAME="Jason"
LNAME="Bourne"

echo "I love" $FNAME $LNAME "movies"
sleep 2
echo
echo "Here I have used two variables, FNAME and LNAME."
sleep 1
echo "In this script, you have learnt how to declare variables and use them."
