#!/bin/bash
clear
mywvar="y"
mycount=0

while [ $mywvar = "y" ] 2> MyErrs.txt
do
  mycount=$(( $mycount + 1 ))
  echo "Welcome to my bash script"
  echo
  sleep 0.5
  echo "Do you want a welcome again? press y if you do and any other letter if you don't"
  read mywvar 2> MyErrs.txt
#  cat hello 2> MyErrs.txt
done

if [ -s MyErrs.txt ]; then

echo "Looks like you have goofed up!!"
echo "By any other letter, I mean anything from a to z"
echo
echo "Here are the error messages"
cat MyErrs.txt

else

echo "Have fun whiling!!"
echo "You have been welcomed" $mycount "number of times!"

fi
