#!/bin/bash

echo "What do you like the most:"

echo "1 - Dark choclate"
sleep 1
echo "2 - Brownie"
sleep 1
echo "3 - Ice cream"
sleep 1
echo "4 - Cold coffee"
sleep 1
echo

echo "Pick a number from the above list:"
read like;

case $like in
   1) echo "I suppose you like the Lindt 70% dark chocs";;
   2) echo "I love hot brownie with vanilla ice-cream";;
   3) echo "I love vanilla ice-cream with strawberry sauce and cream";;
   4) echo "Mmm...coffee on the rocks!!!";;
esac

sleep 2
echo "\nIn this script, you have learnt the case command."
